### ISSUE TITLE
Possibility to pass existing ApiPromise inst. to SubstrateApis 

### ISSUE THREAD

**Issue by nohaapav** [sodazone/ocelloids-sdk#4]
Hi guys, would be great if i can reuse existing ApiPromise within SubstrateApis ..

**Comment by mfornos** [comment]
:wave:

Could you explain a bit your use case so we can better understand how it will work and how it can be best supported.

**Comment by mfornos** [comment]
@nohaapav will any of the following approaches work for you?

**A. Allow subclasses of SubstrateApi to override the internal maps**

Make the internal maps protected and allow the subclasses of SubstrateApis to set the instances.
https://github.com/sodazone/ocelloids/blob/356e3f46d7ea816e4016c271c7c5cf332fd775f2/packages/core/src/apis/substrate-apis.ts#L51-L52
Here, the logic of how to provide the instances is up to the subclass.

**B. Passing the instances in the constructor**

Something like this:
```
new SubstrateApis({
  networkname: {
    apiPromise: existingPromiseInstance,
    apiRx: existingRxInstance
  }
})
```
We should consider these scenarios:
1) Both instances are provided, you pass ApiPromise and ApiRx instances.
2) One instance is provided, either ApiPromise or ApiRx. This requires to pass the `provider` as well, since one will be instantiated lazily.
3) No instance is provided, the current case.

---

For simplicity and flexibility I prefer A over B.
